openapi: 3.0.1
info:
  title: Commvault REST API
  version: LATEST
  description: Commvault APIs
  contact:
    name: Commvault API
paths:
  /V5/Credential/{credentialId}:
    delete:
      x-terraform-resource: Credential
      tags:
      - CredentialManager
      summary: Delete Credential
      operationId: DeleteCredential
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResp'
        '404':
          description: Not Found
      description: Delete Credential whose id has been provided
      parameters:
      - name: credentialId
        in: path
        description: Id of the credentialId
        required: true
        schema:
          type: integer
          format: int32
components:
  schemas:
    GenericResp:
      type: object
      properties:
        errorMessage:
          type: string
          nullable: true
        errorCode:
          type: integer
          format: int32